services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lrb2014hm!
      MYSQL_DATABASE: online_bookstore
    ports:
      - "3307:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql

  eureka:
    image: eureka:0.0.1-SNAPSHOT
    container_name: eureka
    restart: always
    ports:
      - "8761:8761"
    networks:
      - app_network
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/online_bookstore
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: lrb2014hm!

  function:
    image: function:0.0.1-SNAPSHOT
    container_name: function
    restart: always
    ports:
      - "8083:8083"
    networks:
      - app_network
    depends_on:
      - eureka
      - mysql
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka

  microservice:
    image: microservice:0.0.1-SNAPSHOT
    container_name: microservice
    restart: always
    ports:
      - "8082:8082"
    networks:
      - app_network
    depends_on:
      - eureka
      - mysql
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/online_bookstore
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: lrb2014hm!

  backend:
    image: online-bookstore-backend:0.0.1-SNAPSHOT
    container_name: backend
    restart: always
    ports:
      - "8081:8081"
    networks:
      - app_network
    depends_on:
      - eureka
      - mysql
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/online_bookstore
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: lrb2014hm!

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    container_name: gateway
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - eureka
      - function
      - microservice
      - backend
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka

networks:
  app_network:

volumes:
  mysql_data: